// Import the core axios instance and the retry wrapper function from the local index file
import service, { requestWithRetry } from './index'

/**
 * Start report generation
 * @param {Object} data - { simulation_id, force_regenerate? }
 */
export const generateReport = (data) => {
  // Wraps the POST request in 'requestWithRetry' to handle potential transient failures.
  // Arguments: 3 retries, 1000ms initial delay (exponential backoff applied internally).
  return requestWithRetry(() => service.post('/api/report/generate', data), 3, 1000)
}

/**
 * Get report generation status
 * @param {string} reportId
 */
export const getReportStatus = (reportId) => {
  // Performs a GET request to check the current state of the generation task.
  // Uses 'params' to append the report_id as a query string parameter (e.g., ?report_id=123).
  return service.get(`/api/report/generate/status`, { params: { report_id: reportId } })
}

/**
 * Get agent logs (incremental)
 * @param {string} reportId
 * @param {number} fromLine - Start fetching from this line number
 */
export const getAgentLog = (reportId, fromLine = 0) => {
  // Fetches logs specifically generated by the AI agents.
  // The 'fromLine' parameter enables incremental fetching, preventing re-download of old logs.
  // Default value 0 ensures it fetches from the beginning if no offset is specified.
  return service.get(`/api/report/${reportId}/agent-log`, { params: { from_line: fromLine } })
}

/**
 * Get console logs (incremental)
 * @param {string} reportId
 * @param {number} fromLine - Start fetching from this line number
 */
export const getConsoleLog = (reportId, fromLine = 0) => {
  // Fetches system-level console logs for debugging or monitoring backend execution.
  // Uses the same incremental loading strategy as getAgentLog.
  return service.get(`/api/report/${reportId}/console-log`, { params: { from_line: fromLine } })
}

/**
 * Get report details
 * @param {string} reportId
 */
export const getReport = (reportId) => {
  // Retrieves the complete report object, likely including the final content and metadata.
  // The reportId is passed directly in the URL path.
  return service.get(`/api/report/${reportId}`)
}

/**
 * Chat with Report Agent
 * @param {Object} data - { simulation_id, message, chat_history? }
 */
export const chatWithReport = (data) => {
  // Establishes a chat session with the ReportAgent for interactive queries about the report.
  // Uses retry logic because chat interactions are critical and may require stability.
  return requestWithRetry(() => service.post('/api/report/chat', data), 3, 1000)
}